### ISSUE TITLE
_tick maxes out CPU

### ISSUE THREAD

**Issue by theonlypwner** [dpleshkov/serverlistplus-client#1]
ServerList+ v2 eats up a lot of CPU compared to ServerList+ v1, to the point where it's maxing out a CPU core in Chrome with a 165 Hz monitor.

The issue is that `SystemListManager._tick` generates HTML and sets the `innerHTML` of elements every frame, which is heavy on CPU cycles. `_tick` in `serverList.js` has a similar issue with `innerText`.

If I comment out these lines, the CPU utilization drops significantly:

```js
if (self.systemCards[system.id.toString()]) self.systemCards[system.id.toString()].innerHTML = self.getCardHTML(system);
```

```js
let population = systemListProvider.getPopulation();
document.getElementById("countAmerica").innerText = population.America;
document.getElementById("countEurope").innerText = population.Europe;
document.getElementById("countAsia").innerText = population.Asia;
document.getElementById("countTotal").innerText = population.World;
```

**Comment by dpleshkov** [comment]
Fixed in b9a66bd. What used to be the _tick function now only runs when either the `simstatus.json` gets refreshed or the user changes preferences.
